### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by buzzzo** [macontreras3/RPCA_WoL#1]
Is not clear how this fit in cvad enviroment and what is the big picture.

**Comment by macontreras3** [comment]
This feature is specific to the Remote PC Access use case. i.e. physical PCs with the VDA installed to facilitate remote access. Wake on LAN allows you to power on physical PCs when users' want to launch a session to their physical office PC and it's powered off at the time of the request.
Official feature documentation: https://docs.citrix.com/en-us/citrix-virtual-apps-desktops/install-configure/remote-pc-access.html#wake-on-lan
